### PR TITLE
Feature/dutch translation

### PR DESCRIPTION
**Pull request by thedigitalproblemsolver**
Added translation for dutch and translated everything. Some jargon left untranslated because it makes more sense in english.

### CODE REVIEW

**Comment by scrumpypoker** [comment]
Hello @thedigitalproblemsolver , 
Thank you very much for your contribution! We're thrilled to announce that Scrumpy Poker is going out of beta and we have added the missing texts in the master branch. It has been a while since we started and we don't expect much more changes in the texts. We'd be glad if you update your translations with the last changes so that we can merge it and release as soon as you let us know. Please don't hesitate to poke us via e-mail (info@scrumpy.poker) or the web site chat or any other means except Github.

**Comment by thedigitalproblemsolver** [comment]
@scrumpypoker thanks for the message. I saw it a bit late. Hope that this translation now can be merged.

**Comment by scrumpypoker** [comment]
@thedigitalproblemsolver Thank you very much! The next release is planned on 1st of November. This PR will be included.

**Comment by scrumpypoker** [comment]
@thedigitalproblemsolver, the PR says that there are many modified files. There should be one modified file - the new language. Can you please check if for some reason the line endings or something else has changed to the other translations? The PR will be merged immediately after this is resolved. In the meanwhile we will work with the provided translation. It is looking good, one small question - did we properly translate the language label as 'Nederlands'?

image

**Comment by thedigitalproblemsolver** [comment]
@scrumpypoker fixed the PR. Your screenshot is great and has the correct translation.

**Review by scrumpypoker — APPROVED** [review]

**Pull request merged**
